### ISSUE TITLE
Ability to change the font size

### ISSUE THREAD

**Issue by klinker24** [klinker41/article-android#16]
Many apps already have font size settings built in, we should give developers the opportunity to follow those preferences.

This will just require a new extra on the `ArticleIntent` for font size in `sp`. That size should be set for the content of the `TextView`s, with slight deviations for the domain name and the article title

@klinker41 should be very straightforward, do you foresee any issues? I was going to add this this weekend.

**Comment by klinker41** [comment]
No, this will be easy. You won't even have to convert to `sp`, if you just pass the int value into `TextView#setTextSize` then that should work. 

You'll just have to change some font sizes appropriately, things like the title should be larger than the paragraphs.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/article-android/commit/80bff3c502179996772265882c95060eefce80af
