### ISSUE TITLE
Cache data locally on device so that we can preload data if desired

### ISSUE THREAD

**Issue by klinker41** [klinker41/article-android#4]
We should allow the user to invoke the APIs directly if they wish instead of starting it via the activity. This will allow them to preload the article in the background so that it is available immediately to the user. 

Use case for this would be an offline reader app, downloading an article instantly when an SMS is received with a link so that there is no load time later, etc. 

This would also help to give the perception of a speedy app. If we need to go to a chrome custom tab instead of our own article, then that could be done instantly instead of waiting for the result from our server.

Implementation wise, a simple SQLite database should work fine to store the article information and HTML, very similar to what Source currently has. Then we would just need to query that database before making a request to the server for the data.

We would also have to preload the images so that they are available when offline and viewing an article. I believe that talon does this already, so we could borrow that implementation.

* [x] set up database
* [x] store article in database after getting response from server
* [x] load article where available before making request to server
* [x] preload images after storing the article in the database
* [x] display preloaded images (I'm guessing we can do this automatically with glide, but I can use network monitor to confirm this)
* [x] add preloading apis to `ArticleUtils` (also update the readme on how to use this)
* [ ] add way to set how often cache should be invalidated (or never if they want to handle it themselves)
* [ ] invalidate old images and articles in the cache

**Comment by klinker24** [comment]
You shouldn't have to worry about invalidating images in the cache. Glide/Android will handle that for you

**Comment by klinker41** [comment]
Ok, I'm not going to worry about this anymore then. I had to invalidate articles in Source after a set amount of time, but that was because we were downloading so much content. Since these are just text for random articles that you open occasionally, it shouldn't add up to a significant amount for years.

**Comment by klinker24** [comment]
Yeah I wouldn't think so, but we are more casual users haha it may be a few hundred MB for some users after awhile!
